# Generated by Django 6.0.2 on 2026-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='last_emergency_alert',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
