# Generated by Django 6.0.2 on 2026-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthprofile_last_emergency_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
